name: Riverbraid CI Pipeline

concurrency:
  group: riverbraid-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - copilot/ri-core-scaffold
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache

      - name: Build Docker image (local CI image, not pushed)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: riverbraid/riverbraid-substrate-core:ci-${{ github.sha }}

  deploy-ui:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: https://riverbraid.github.io/riverbraid-substrate-core/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy /ui to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui
